#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:file:~/data/customers_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=kalunge
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:mysql://localhost:3306/microservices
#spring.datasource.username=root
#spring.datasource.password=rootpass
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/microservices
    username: root
    password: rootpass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: CUSTOMER-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}